# Generated by Django 3.1.1 on 2020-09-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table=None,
        ),
    ]
